version: "3.9"
services:
  app:
    build: ./backend
    container_name: quizsql-php
    ports:
      - "3001:80"          # API: http://localhost:3001
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=quizdb
      - DB_USER=quizuser
      - DB_PASS=quizpass
      - TZ=Asia/Tokyo
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: quizsql-db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpw
      - MYSQL_DATABASE=quizdb
      - MYSQL_USER=quizuser
      - MYSQL_PASSWORD=quizpass
      - TZ=Asia/Tokyo
    ports:
      - "3307:3306"        # 既存の3306と同時起動でも衝突しない
    volumes:
      - dbdata:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d:ro

volumes:
  dbdata:
